In [1]:
import numpy as np

In [8]:
ih = np.load("ihdp.npz")

ih.files

['x', 't', 'yf', 'ycf', 'ite']

In [13]:
ih['x'][:10]

array([[ 1.39739503,  0.99634625, -1.10562395, -0.87960599,  0.30856884,
        -1.02340239,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  1.        ,  0.        ,
         0.        ,  1.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ],
       [ 0.26903265,  0.19681812,  0.38382797,  0.16170253, -0.62918919,
         1.46083153,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.05153683,  1.79587438, -1.10562395,  0.16170253, -0.62918919,
         0.96398475,  1.        ,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  1.        ,  0

In [20]:
ih['yf'][:10]

array([[4.77123234],
       [2.95627286],
       [4.16416445],
       [6.17230732],
       [7.83446893],
       [0.75373794],
       [6.20815481],
       [7.63018615],
       [3.25830846],
       [0.3112368 ]])

In [9]:
jb = np.load("jobs.npz")

jb.files

['x', 't', 'y', 'e']

In [14]:
jb['x'][:10]

array([[-0.61428209,  1.46472657,  0.        ,  0.        ,  1.        ,
         0.        ,  2.39325   ,  2.74619647, -0.65331121, -0.65691271,
         1.62753104,  2.46233663,  2.93724407,  0.        ,  0.        ,
         2.84390896,  0.        ],
       [-0.80246274,  0.10183499,  0.        ,  0.        ,  1.        ,
         0.        ,  0.10988519,  0.49827132, -0.78528431, -0.74340718,
        -0.02250229, -0.1771929 ,  0.08253676,  0.        ,  0.        ,
         0.03842226,  0.        ],
       [-0.89655306, -0.23888791,  1.        ,  0.        ,  1.        ,
         1.        , -0.08521244, -0.14809694, -0.84731167, -0.78160584,
        -0.36134842, -0.28622144, -0.3036151 ,  0.        ,  0.        ,
        -0.19130379,  0.        ],
       [-0.89655306, -0.23888791,  0.        ,  0.        ,  0.        ,
         1.        ,  0.40558116,  0.32559351, -0.84731167, -0.78160584,
        -0.36134842,  0.02301955, -0.03962994,  0.        ,  0.        ,
         0.17310822

In [23]:
jb['y'][:10]

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0]], dtype=uint8)